# Generated by Django 5.2.4 on 2025-07-30 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0005_alter_contact_unique_together_alter_contact_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='description',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
